# Generated by Django 6.0.3 on 2026-03-29 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_pagevisit'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PageVisit',
        ),
    ]
