# Generated by Django 6.0.3 on 2026-04-07 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0006_recommendationcache_userpreference_listingview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listingview',
            name='session_id',
            field=models.CharField(blank=True, max_length=110, null=True),
        ),
    ]
