# Generated by Django 6.0.3 on 2026-04-07 11:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0009_alter_report_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recommendationcache',
            options={},
        ),
        migrations.AlterModelOptions(
            name='userpreference',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='listingview',
            name='listings_li_user_id_cbac09_idx',
        ),
        migrations.RemoveIndex(
            model_name='listingview',
            name='listings_li_listing_7b82c2_idx',
        ),
        migrations.RemoveIndex(
            model_name='listingview',
            name='listings_li_session_f379b7_idx',
        ),
        migrations.RemoveField(
            model_name='userpreference',
            name='preferred_districts',
        ),
        migrations.RemoveField(
            model_name='userpreference',
            name='price_max',
        ),
        migrations.RemoveField(
            model_name='userpreference',
            name='price_min',
        ),
        migrations.AlterField(
            model_name='listingview',
            name='listing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendation_views', to='listings.listing'),
        ),
        migrations.AlterField(
            model_name='listingview',
            name='session_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='listingview',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recommendation_views', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='recommendationcache',
            name='recommendations',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='userpreference',
            name='preferred_categories',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='userpreference',
            name='preferred_listing_types',
            field=models.JSONField(default=list),
        ),
        migrations.RemoveField(
            model_name='listingview',
            name='ip_address',
        ),
    ]
