# Generated by Django 6.0.3 on 2026-04-11 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0011_userpreference_location_preferences_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='featured_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='featured_priority',
            field=models.IntegerField(default=0, help_text='0=Normal, 1=Premium, 2=Business'),
        ),
    ]
