# Generated by Django 6.0.3 on 2026-04-05 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('general', 'General'), ('subscription_approved', 'Subscription Approved'), ('subscription_rejected', 'Subscription Rejected'), ('subscription_expired', 'Subscription Expired')], default='general', max_length=50),
        ),
    ]
