# Generated by Django 6.0.3 on 2026-04-05 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_alter_usersubscription_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='max_images_per_listing',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
