# Generated by Django 6.0.3 on 2026-04-05 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0003_subscriptionplan_max_images_per_listing'),
    ]

    operations = [
    ]
