# Generated by Django 6.0.3 on 2026-04-11 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('rw', 'Kinyarwanda')], default='en', max_length=2),
        ),
    ]
